### ISSUE TITLE
How to deblur a single motion blurred image?

### ISSUE THREAD

**Issue by jiachen0212** [radimspetlik/SI-DDPM-FMO#2]
Thanks for your work. I want to use code to deblur a single motion blurred image. I have studied the fmo_deblurring_benchmark.py script, and it seems that it needs the ground truth information of the gt_bbox box. How can I modify it to skip this supervision information and deblur a single motion blurred image?

**Comment by rasemailcz** [comment]
Dear @jiachen0212 ,

The bounding box is there since it is required by the benchmarks. You actually do not need to provide a bounding box.

The deblurring and trajectory and shape estimation happens from the line 166 in fmo_deblurring_benchmark.py [https://github.com/radimspetlik/SI-DDPM-FMO/blob/217a300bf7999d8518468e3bc7c272f96aa1a3ab/fmo_deblurring_benchmark.py#L166](url) and the image sequence is created on the line 247 [https://github.com/radimspetlik/SI-DDPM-FMO/blob/217a300bf7999d8518468e3bc7c272f96aa1a3ab/fmo_deblurring_benchmark.py#L247](url).

Hope this helps...
